In [4]:
import numpy as np

In [5]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [6]:
#vector from list
vec=np.array([1,2,3])
print(vec)
#matrices for list 
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('-----')
print(mat)
print('-----')
print(mat.T)

[1 2 3]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# Creating vector another method arange ( start , end, step) end is not included 
vec2=np.arange(0,15)
print(vec2)
#specifying step size in arange
vec3=np.arange(3,27,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  9 15 21]


In [8]:
#linspace inclusive start and end create equal interval ( start, end, number of items between start and end)
vec4=np.linspace(0,5,10)
print(vec4)
#reshape(row, column)
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [9]:
#zero matrix
mat2=np.zeros([5,3])
print(mat2)
#ones matrix
mat3=np.ones([5,3])
print(mat3)
#identity matrix since its a square matrix only one column is required
mat4=np.eye(5)
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#addion and subrtraction of arrays
vec5=np.arange(1,8)
vec6=np.arange(3,10)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]
[ 4  6  8 10 12 14 16]
[ 3  8 15 24 35 48 63]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714]
[1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]


In [11]:
#matrix multiplication
print(mat)
print(vec)
product=np.matmul(mat,vec)
print(product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[14 32 50]


In [12]:
print(np.linalg.solve(mat,product))

[-0.8  5.6  1.2]


In [13]:
vecsol=np.array([-0.8 , 5.6,  1.2])

In [14]:
product2=np.matmul(mat,vecsol)
print(product2)

[14. 32. 50.]


In [15]:
#invesrse of a matrix
print(np.linalg.inv(mat))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [16]:
print(np.matmul(np.linalg.inv(mat),mat))

[[ 12.   16.   12. ]
 [-10.  -16.   -6. ]
 [  1.5   4.    2.5]]


In [17]:
#find out unique values in an array
vec7=np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
#every entry in the array for numpy has to be same data type auto converts 

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']


In [18]:
print(np.unique(vec7))

['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [19]:
vec7_e=np.array([6,7,8.0])
print(vec7_e)

[6. 7. 8.]


In [32]:
#random matrix
rand_mat=np.random.rand(5,5) #uniform random variable 
print(rand_mat)
print('')
rand_mat2=np.random.randn(10,5) #standard normal random
print(rand_mat2)

[[0.21241286 0.95638616 0.83771219 0.62448201 0.11537589]
 [0.58815589 0.49815423 0.05200061 0.53909279 0.46463918]
 [0.73770866 0.25816512 0.67987598 0.07889392 0.05923796]
 [0.88233058 0.32615171 0.97756927 0.77333598 0.35425282]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]

[[-1.47299477  0.51112034  0.53637127  0.12547953 -1.36202641]
 [ 0.67730878  1.801253    0.9936483   0.14372381  1.82818462]
 [ 0.37868084  2.0258247   0.97490817 -1.3476588   1.56702633]
 [-0.8272471   0.1613421   2.3825726  -0.78461779 -1.42792125]
 [ 1.99087676  0.50278713 -0.17341499  1.13097518  0.72734424]
 [-0.82541982  0.83768007  1.14085648  1.05183597  2.22127305]
 [-0.37376319  2.04260505 -0.06964045  0.06647203 -3.85037542]
 [-2.20294041  1.31026636  0.93357573 -1.36456805 -0.44488865]
 [-1.66062131  0.14552951  0.58750342  0.19836348  0.05690711]
 [ 1.10981388 -0.45205893 -1.11302527  1.48177205 -0.26029078]]


In [34]:
#mean , std. deviation
print(np.mean(rand_mat))
print(np.mean(rand_mat2))
print(np.std(rand_mat2))

0.4680285505486285
0.2326081701212533
1.2647623061495046


In [35]:
#Minimum and Maximum
print(np.min(rand_mat2))
print(np.max(rand_mat2))

-3.850375421048534
2.3825725998931255


In [38]:
#how to access entries in numpy vector
rand_vec=np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.04031547 -0.2490956  -1.13725653 -0.21146442  0.80616397  0.02453691
 -1.14375397  0.17348999  0.0769856  -0.23762321  2.06988242 -0.21291156
  1.19846212 -0.36085721  1.24106994  0.64675993  0.74620413  1.00572722
 -1.2927079 ]
-1.1437539658043692


In [40]:
# we can access multiple entries at once using:
print(rand_vec[4:9]) # number to the right of : is exclusive

[ 0.80616397  0.02453691 -1.14375397  0.17348999  0.0769856 ]


In [42]:
# we can also access non-consequtive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.04031547 -0.21146442 -1.14375397 -0.23762321  1.19846212]


In [45]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])#row index, column index 

[[0.21241286 0.95638616 0.83771219 0.62448201 0.11537589]
 [0.58815589 0.49815423 0.05200061 0.53909279 0.46463918]
 [0.73770866 0.25816512 0.67987598 0.07889392 0.05923796]
 [0.88233058 0.32615171 0.97756927 0.77333598 0.35425282]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]
0.052000614275849344
0.052000614275849344


In [46]:
print(rand_mat[0:2,1:3])

[[0.95638616 0.83771219]
 [0.49815423 0.05200061]]


In [51]:
#lets change some values in array!
print(rand_vec)
rand_vec[3:5]=4
print(rand_vec)
rand_vec[3:5]=[1,2]
print(rand_vec)

[-1.04031547 -0.2490956  -1.13725653  1.          2.          0.02453691
 -1.14375397  0.17348999  0.0769856  -0.23762321  2.06988242 -0.21291156
  1.19846212 -0.36085721  1.24106994  0.64675993  0.74620413  1.00572722
 -1.2927079 ]
[-1.04031547 -0.2490956  -1.13725653  4.          4.          0.02453691
 -1.14375397  0.17348999  0.0769856  -0.23762321  2.06988242 -0.21291156
  1.19846212 -0.36085721  1.24106994  0.64675993  0.74620413  1.00572722
 -1.2927079 ]
[-1.04031547 -0.2490956  -1.13725653  1.          2.          0.02453691
 -1.14375397  0.17348999  0.0769856  -0.23762321  2.06988242 -0.21291156
  1.19846212 -0.36085721  1.24106994  0.64675993  0.74620413  1.00572722
 -1.2927079 ]


In [55]:
print(rand_mat)
rand_mat[1:4,3:5]=0
print(rand_mat)

[[0.21241286 0.95638616 0.83771219 0.62448201 0.11537589]
 [0.58815589 0.49815423 0.05200061 0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.77333598 0.35425282]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]
[[0.21241286 0.95638616 0.83771219 0.62448201 0.11537589]
 [0.58815589 0.49815423 0.05200061 0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]


In [56]:
sub_mat=rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:]=3
print(rand_mat)

[[0.21241286 0.95638616 0.83771219]
 [0.58815589 0.49815423 0.05200061]]
[[3.         3.         3.         0.62448201 0.11537589]
 [3.         3.         3.         0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]


In [57]:
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [61]:
sub_mat2=rand_mat[0:2,0:3].copy()
print(sub_mat2)
sub_mat2[:]=99
print(sub_mat)
print(sub_mat2)
print(rand_mat)


[[3. 3. 3.]
 [3. 3. 3.]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.62448201 0.11537589]
 [3.         3.         3.         0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]


In [64]:
#indexing with logicals 
rand_vec=np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.56594558  0.06277426 -0.94090112 -0.19227318 -2.06241706 -0.63061843
 -0.20372553 -1.46982045 -0.20158221  0.00213349 -0.32827739  0.03137264
  1.07887974  1.04961296  0.2296209 ]
[ True  True False False False False False False False  True False  True
  True  True  True]
[0.56594558 0.06277426 0.00213349 0.03137264 1.07887974 1.04961296
 0.2296209 ]


In [65]:
print(rand_mat2)

[[-1.47299477  0.51112034  0.53637127  0.12547953 -1.36202641]
 [ 0.67730878  1.801253    0.9936483   0.14372381  1.82818462]
 [ 0.37868084  2.0258247   0.97490817 -1.3476588   1.56702633]
 [-0.8272471   0.1613421   2.3825726  -0.78461779 -1.42792125]
 [ 1.99087676  0.50278713 -0.17341499  1.13097518  0.72734424]
 [-0.82541982  0.83768007  1.14085648  1.05183597  2.22127305]
 [-0.37376319  2.04260505 -0.06964045  0.06647203 -3.85037542]
 [-2.20294041  1.31026636  0.93357573 -1.36456805 -0.44488865]
 [-1.66062131  0.14552951  0.58750342  0.19836348  0.05690711]
 [ 1.10981388 -0.45205893 -1.11302527  1.48177205 -0.26029078]]


In [66]:
print(rand_mat2[rand_mat2>0])

[0.51112034 0.53637127 0.12547953 0.67730878 1.801253   0.9936483
 0.14372381 1.82818462 0.37868084 2.0258247  0.97490817 1.56702633
 0.1613421  2.3825726  1.99087676 0.50278713 1.13097518 0.72734424
 0.83768007 1.14085648 1.05183597 2.22127305 2.04260505 0.06647203
 1.31026636 0.93357573 0.14552951 0.58750342 0.19836348 0.05690711
 1.10981388 1.48177205]


In [68]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5]=-5
print(rand_vec)

[-5.00000000e+00  6.27742588e-02 -9.40901122e-01 -1.92273182e-01
 -2.06241706e+00 -6.30618429e-01 -2.03725529e-01 -1.46982045e+00
 -2.01582205e-01  2.13349479e-03 -3.28277393e-01  3.13726418e-02
 -5.00000000e+00 -5.00000000e+00  2.29620900e-01]

[-5.00000000e+00  6.27742588e-02 -9.40901122e-01 -1.92273182e-01
 -2.06241706e+00 -6.30618429e-01 -2.03725529e-01 -1.46982045e+00
 -2.01582205e-01  2.13349479e-03 -3.28277393e-01  3.13726418e-02
 -5.00000000e+00 -5.00000000e+00  2.29620900e-01]


In [69]:
#just one np array npy ext
np.save('saved_file_name',rand_mat2)

In [70]:
#more than one array you need to zip it in format given below
np.savez('zipped_saved_file_name',rand_mat2=rand_mat2,rand_mat=rand_mat)

In [76]:
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_saved_file_name.npz')
print(loaded_vec)
print('')
print(loaded_zip)

[[-1.47299477  0.51112034  0.53637127  0.12547953 -1.36202641]
 [ 0.67730878  1.801253    0.9936483   0.14372381  1.82818462]
 [ 0.37868084  2.0258247   0.97490817 -1.3476588   1.56702633]
 [-0.8272471   0.1613421   2.3825726  -0.78461779 -1.42792125]
 [ 1.99087676  0.50278713 -0.17341499  1.13097518  0.72734424]
 [-0.82541982  0.83768007  1.14085648  1.05183597  2.22127305]
 [-0.37376319  2.04260505 -0.06964045  0.06647203 -3.85037542]
 [-2.20294041  1.31026636  0.93357573 -1.36456805 -0.44488865]
 [-1.66062131  0.14552951  0.58750342  0.19836348  0.05690711]
 [ 1.10981388 -0.45205893 -1.11302527  1.48177205 -0.26029078]]



In [77]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

[[3.         3.         3.         0.62448201 0.11537589]
 [3.         3.         3.         0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]

[[-1.47299477  0.51112034  0.53637127  0.12547953 -1.36202641]
 [ 0.67730878  1.801253    0.9936483   0.14372381  1.82818462]
 [ 0.37868084  2.0258247   0.97490817 -1.3476588   1.56702633]
 [-0.8272471   0.1613421   2.3825726  -0.78461779 -1.42792125]
 [ 1.99087676  0.50278713 -0.17341499  1.13097518  0.72734424]
 [-0.82541982  0.83768007  1.14085648  1.05183597  2.22127305]
 [-0.37376319  2.04260505 -0.06964045  0.06647203 -3.85037542]
 [-2.20294041  1.31026636  0.93357573 -1.36456805 -0.44488865]
 [-1.66062131  0.14552951  0.58750342  0.19836348  0.05690711]
 [ 1.10981388 -0.45205893 -1.11302527  1.48177205 -0.26029078]]


In [78]:
# we can also save/load as text files ... but only single variables 
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt=np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.62448201 0.11537589]
 [3.         3.         3.         0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]

[[3.         3.         3.         0.62448201 0.11537589]
 [3.         3.         3.         0.         0.        ]
 [0.73770866 0.25816512 0.67987598 0.         0.        ]
 [0.88233058 0.32615171 0.97756927 0.         0.        ]
 [0.25243221 0.19559491 0.47533804 0.369212   0.3922028 ]]
