In [5]:
import numpy as np
demo_array=np.arange(0,10)
print(demo_array)
print(demo_array<3)

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True False False False False False False False]


In [6]:
print(demo_array[demo_array<6])

[0 1 2 3 4 5]


In [7]:
np.max(demo_array)

9

In [10]:
demo_matrix=np.array(([13,35,74,48],[27,37,37,38],[73,39,93,39]))
demo_matrix

array([[13, 35, 74, 48],
       [27, 37, 37, 38],
       [73, 39, 93, 39]])

In [12]:
demo_matrix[:,(1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [14]:
demo_array=np.arange(10,21)
demo_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
subset_demo_array = demo_array[0:7]
subset_demo_array

array([10, 11, 12, 13, 14, 15, 16])

In [18]:
subset_demo_array[:]=101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])